### ISSUE TITLE
Fix flaky test TestRelayHandlesClosedPeers

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel-go#454]
https://travis-ci.org/uber/tchannel-go/jobs/146206950

Logs:
```
--- FAIL: TestRelayHandlesClosedPeers (0.31s)
	<autogenerated>:31: Unexpected log: [Warn]: Connection error. [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205} {site read frames} {error read tcp 127.0.0.1:43572->127.0.0.1:51205: read: connection reset by peer}]
	<autogenerated>:29: Debug logs:
		21:10:46.302894 [D] NewChannel created at goroutine 2520 [running]:
		github.com/uber/tchannel-go.getStacks(0xc821841400, 0x0, 0x0, 0x0)
			github.com/uber/tchannel-go/_test/_obj_test/introspection.go:447 +0xff
		github.com/uber/tchannel-go.registerNewChannel(0xc821841440)
			github.com/uber/tchannel-go/_test/_obj_test/all_channels.go:39 +0x79
		github.com/uber/tchannel-go.NewChannel(0xb31df8, 0x4, 0xc82162b268, 0xb2cfe0, 0x0, 0x0)
			github.com/uber/tchannel-go/_test/_obj_test/channel.go:220 +0x111b
		github.com/uber/tchannel-go/testutils.NewServerChannel(0xc82162b268, 0xc8201d1b90, 0x0, 0x0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/channel.go:51 +0x7e5
		github.com/uber/tchannel-go/testutils.newServer(0x2b137eecfc18, 0xc8201d1b90, 0xc8208f7200, 0xf8)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/channel_t.go:71 +0x6c
		github.com/uber/tchannel-go/testutils.(*TestServer).addChannel(0xc8201d1b90, 0xc43518, 0xc8208f7200, 0xc82162b658)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:234 +0x81
		github.com/uber/tchannel-go/testutils.(*TestServer).NewServer(0xc8201d1b90, 0xc82162b8c0, 0xc822a75500)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:204 +0xb6
		github.com/uber/tchannel-go/testutils.NewTestServer(0x2b137eecfaa8, 0xc820fe3cb0, 0xc82162b8c0, 0xc8200de900)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:85 +0x2bb
		github.com/uber/tchannel-go/testutils.withServer(0x2b137eecfaa8, 0xc820fe3cb0, 0xc82162b8c0, 0xc82162be48)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:420 +0x4a
		github.com/uber/tchannel-go/testutils.WithTestServer(0x2b137eecfaa8, 0xc820fe3cb0, 0xc82162b7c8, 0xc82162be48)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:116 +0x2d1
		github.com/uber/tchannel-go_test.TestRelayHandlesClosedPeers(0xc820fe3cb0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/relay_test.go:112 +0x20c
		testing.tRunner(0xc820fe3cb0, 0xe4b2a8)
			/tmp/workdir/go/src/testing/testing.go:456 +0xdd
		created by testing.RunTests
			/tmp/workdir/go/src/testing/testing.go:561 +0xaa4
		 [{service test} {process test-36735}]
		21:10:46.303086 [D] test-36735 (test) listening on 127.0.0.1:36735 [{service test} {process test-36735} {hostPort 127.0.0.1:36735}]
		21:10:46.313399 [D] created for test (test-36735) local: 127.0.0.1:36735 remote: 127.0.0.1:40408 [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.315178 [D] New active inbound connection for peer 127.0.0.1:40408 [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.315312 [D] Writing frame messageTypeInitRes[1] [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.317283 [D] Creating new inbound message exchange for [messageTypeCallReq:2] [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408} {exchange inbound}]
		21:10:46.317837 [D] Received incoming call for test from 127.0.0.1:40408(relay-43572) [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.318312 [D] Dispatching test:echo from 127.0.0.1:40408(relay-43572) [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.318996 [D] Removing inbound message exchange 2 [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408} {exchange inbound}]
		21:10:46.319332 [D] Writing frame messageTypeCallRes[2] [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.321426 [I] Channel.Close called [{service test} {process test-36735} {hostPort 127.0.0.1:36735}]
		21:10:46.321573 [D] Connection Close [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.321903 [D] checkExchanges updated connection state to connectionClosed [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.322120 [I] Removed peer 127.0.0.1:40408 from root peer list [{service test} {process test-36735} {hostPort 127.0.0.1:36735}]
		21:10:46.322289 [D] ConnectionCloseStateChange channel state = ChannelClosed connection minState = connectionClosed [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.323595 [D] Closing underlying network connection [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.323772 [D] Ignoring error after connection was closed: read tcp 127.0.0.1:36735->127.0.0.1:40408: use of closed network connection [{service test} {process test-36735} {hostPort 127.0.0.1:36735} {connID 475} {localAddr 127.0.0.1:36735} {remoteAddr 127.0.0.1:40408}]
		21:10:46.605948 [D] TEST: Test function complete [{service test} {process test-36735} {hostPort 127.0.0.1:36735}]
		21:10:46.609390 [D] TEST: TestServer is closing and verifying channel [{service test} {process test-36735} {hostPort 127.0.0.1:36735}]
		21:10:46.609458 [I] Channel.Close called [{service test} {process test-36735} {hostPort 127.0.0.1:36735}]
	<autogenerated>:29: Debug logs:
		21:10:46.303973 [D] NewChannel created at goroutine 2520 [running]:
		github.com/uber/tchannel-go.getStacks(0xc821841700, 0x0, 0x0, 0x0)
			github.com/uber/tchannel-go/_test/_obj_test/introspection.go:447 +0xff
		github.com/uber/tchannel-go.registerNewChannel(0xc8218417a0)
			github.com/uber/tchannel-go/_test/_obj_test/all_channels.go:39 +0x79
		github.com/uber/tchannel-go.NewChannel(0xb315c0, 0x5, 0xc82216f1d0, 0xb2cfe0, 0x0, 0x0)
			github.com/uber/tchannel-go/_test/_obj_test/channel.go:220 +0x111b
		github.com/uber/tchannel-go/testutils.NewServerChannel(0xc82216f1d0, 0xc8201d1b90, 0x0, 0x0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/channel.go:51 +0x7e5
		github.com/uber/tchannel-go/testutils.newServer(0x2b137eecfc18, 0xc8201d1b90, 0xc8208f7300, 0xf8)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/channel_t.go:71 +0x6c
		github.com/uber/tchannel-go/testutils.(*TestServer).addChannel(0xc8201d1b90, 0xc43518, 0xc8208f7300, 0xc82216f630)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:234 +0x81
		github.com/uber/tchannel-go/testutils.(*TestServer).addRelay(0xc8201d1b90, 0xc82216f8b0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:223 +0x50f
		github.com/uber/tchannel-go/testutils.NewTestServer(0x2b137eecfaa8, 0xc820fe3cb0, 0xc82216f8b0, 0xc8200de900)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:87 +0x313
		github.com/uber/tchannel-go/testutils.withServer(0x2b137eecfaa8, 0xc820fe3cb0, 0xc82216f8b0, 0xc82216fe38)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:420 +0x4a
		github.com/uber/tchannel-go/testutils.WithTestServer(0x2b137eecfaa8, 0xc820fe3cb0, 0xc82216f7b8, 0xc82216fe38)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:116 +0x2d1
		github.com/uber/tchannel-go_test.TestRelayHandlesClosedPeers(0xc820fe3cb0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/relay_test.go:112 +0x20c
		testing.tRunner(0xc820fe3cb0, 0xe4b2a8)
			/tmp/workdir/go/src/testing/testing.go:456 +0xdd
		created by testing.RunTests
			/tmp/workdir/go/src/testing/testing.go:561 +0xaa4
		 [{service relay} {process relay-43572}]
		21:10:46.304082 [D] relay-43572 (relay) listening on 127.0.0.1:43572 [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572}]
		21:10:46.306022 [D] created for relay (relay-43572) local: 127.0.0.1:43572 remote: 127.0.0.1:51205 [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205}]
		21:10:46.308217 [D] New active inbound connection for peer 127.0.0.1:51205 [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205}]
		21:10:46.308754 [D] Writing frame messageTypeInitRes[1] [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205}]
		21:10:46.313314 [D] created for relay (relay-43572) local: 127.0.0.1:40408 remote: 127.0.0.1:36735 [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735}]
		21:10:46.314008 [D] Creating new outbound message exchange for [messageTypeInitReq:1] [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735} {exchange outbound}]
		21:10:46.314452 [D] Writing frame messageTypeInitReq[1] [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735}]
		21:10:46.315701 [D] New active outbound connection for peer 127.0.0.1:36735 [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735}]
		21:10:46.316043 [D] forwarding outbound messageTypeInitRes[1] [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735} {exchange outbound}]
		21:10:46.316260 [D] Removing outbound message exchange 1 [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735} {exchange outbound}]
		21:10:46.316899 [D] Writing frame messageTypeCallReq[2] [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735}]
		21:10:46.320063 [D] Writing frame messageTypeCallRes[2] [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205}]
		21:10:46.324431 [D] Writing frame messageTypeCallReq[3] [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735}]
		21:10:46.324653 [D] Connection got EOF [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735}]
		21:10:46.324764 [D] Connection Close [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735}]
		21:10:46.325077 [D] stopping 0 exchanges due to error: tchannel error ErrCodeNetwork: EOF [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735} {exchange outbound}]
		21:10:46.325209 [D] stopping 0 exchanges due to error: tchannel error ErrCodeNetwork: EOF [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735} {exchange inbound}]
		21:10:46.606196 [D] Writing frame messageTypeError[3] [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205}]
		21:10:46.606956 [D] checkExchanges updated connection state to connectionClosed [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735}]
		21:10:46.607407 [D] Closing underlying network connection [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 474} {localAddr 127.0.0.1:40408} {remoteAddr 127.0.0.1:36735}]
		21:10:46.607842 [D] TEST: TestServer is closing and verifying channel [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572}]
		21:10:46.607934 [I] Channel.Close called [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572}]
		21:10:46.608141 [W] Connection error. [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205} {site read frames} {error read tcp 127.0.0.1:43572->127.0.0.1:51205: read: connection reset by peer}]
		21:10:46.608120 [D] Connection Close [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205}]
		21:10:46.608275 [D] Connection Close [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205}]
		21:10:46.608433 [D] stopping 0 exchanges due to error: tchannel error ErrCodeNetwork: read tcp 127.0.0.1:43572->127.0.0.1:51205: read: connection reset by peer [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205} {exchange outbound}]
		21:10:46.608730 [D] checkExchanges updated connection state to connectionClosed [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205}]
		21:10:46.608834 [D] stopping 0 exchanges due to error: tchannel error ErrCodeNetwork: read tcp 127.0.0.1:43572->127.0.0.1:51205: read: connection reset by peer [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205} {exchange inbound}]
		21:10:46.609017 [I] Removed peer 127.0.0.1:51205 from root peer list [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572}]
		21:10:46.609024 [D] Closing underlying network connection [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205}]
		21:10:46.609229 [D] ConnectionCloseStateChange channel state = ChannelClosed connection minState = connectionClosed [{service relay} {process relay-43572} {hostPort 127.0.0.1:43572} {connID 472} {localAddr 127.0.0.1:43572} {remoteAddr 127.0.0.1:51205}]
	<autogenerated>:29: Debug logs:
		21:10:46.304928 [D] NewChannel created at goroutine 2520 [running]:
		github.com/uber/tchannel-go.getStacks(0xc821841b00, 0x0, 0x0, 0x0)
			github.com/uber/tchannel-go/_test/_obj_test/introspection.go:447 +0xff
		github.com/uber/tchannel-go.registerNewChannel(0xc821841b00)
			github.com/uber/tchannel-go/_test/_obj_test/all_channels.go:39 +0x79
		github.com/uber/tchannel-go.NewChannel(0xb2f958, 0x6, 0xc82216f068, 0xb2cfe0, 0x0, 0x0)
			github.com/uber/tchannel-go/_test/_obj_test/channel.go:220 +0x111b
		github.com/uber/tchannel-go/testutils.NewClientChannel(0xc82216f068, 0xc8201d1b90, 0x0, 0x0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/channel.go:74 +0x45c
		github.com/uber/tchannel-go/testutils.newClient(0x2b137eecfc18, 0xc8201d1b90, 0xc8208f7400, 0xf8)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/channel_t.go:85 +0x6c
		github.com/uber/tchannel-go/testutils.(*TestServer).addChannel(0xc8201d1b90, 0xc43510, 0xc8208f7400, 0xb2fd98)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:234 +0x81
		github.com/uber/tchannel-go/testutils.(*TestServer).NewClient(0xc8201d1b90, 0xc82216f5f0, 0xc8201609c0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:199 +0x9d
		github.com/uber/tchannel-go_test.TestRelayHandlesClosedPeers.func1(0xc8201d1b90)
			/home/travis/gopath/src/github.com/uber/tchannel-go/relay_test.go:101 +0x231
		github.com/uber/tchannel-go/testutils.withServer(0x2b137eecfaa8, 0xc820fe3cb0, 0xc82216f8b0, 0xc82216fe38)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:425 +0x90
		github.com/uber/tchannel-go/testutils.WithTestServer(0x2b137eecfaa8, 0xc820fe3cb0, 0xc82216f7b8, 0xc82216fe38)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:116 +0x2d1
		github.com/uber/tchannel-go_test.TestRelayHandlesClosedPeers(0xc820fe3cb0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/relay_test.go:112 +0x20c
		testing.tRunner(0xc820fe3cb0, 0xe4b2a8)
			/tmp/workdir/go/src/testing/testing.go:456 +0xdd
		created by testing.RunTests
			/tmp/workdir/go/src/testing/testing.go:561 +0xaa4
		 [{service client} {process client-1243}]
		21:10:46.306013 [D] created for client (client-1243) local: 127.0.0.1:51205 remote: 127.0.0.1:43572 [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572}]
		21:10:46.306617 [D] Creating new outbound message exchange for [messageTypeInitReq:1] [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572} {exchange outbound}]
		21:10:46.307315 [D] Writing frame messageTypeInitReq[1] [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572}]
		21:10:46.309255 [D] New active outbound connection for peer 127.0.0.1:43572 [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572}]
		21:10:46.309648 [D] forwarding outbound messageTypeInitRes[1] [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572} {exchange outbound}]
		21:10:46.309973 [D] Removing outbound message exchange 1 [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572} {exchange outbound}]
		21:10:46.310531 [D] Creating new outbound message exchange for [messageTypeCallReq:2] [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572} {exchange outbound}]
		21:10:46.311843 [D] Writing frame messageTypeCallReq[2] [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572}]
		21:10:46.320399 [D] forwarding outbound messageTypeCallRes[2] [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572} {exchange outbound}]
		21:10:46.321132 [D] Removing outbound message exchange 2 [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572} {exchange outbound}]
		21:10:46.322607 [D] Creating new outbound message exchange for [messageTypeCallReq:3] [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572} {exchange outbound}]
		21:10:46.323381 [D] Writing frame messageTypeCallReq[3] [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572}]
		21:10:46.605001 [D] reader failed: tchannel error ErrCodeTimeout: timeout existing err: <nil> [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572} {Out-Response 3}]
		21:10:46.605256 [D] Removing outbound message exchange 3 [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572} {exchange outbound}]
		21:10:46.605785 [D] reader failed: tchannel error ErrCodeTimeout: timeout existing err: tchannel error ErrCodeTimeout: timeout [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572} {Out-Response 3}]
		21:10:46.606025 [D] TEST: TestServer is closing and verifying channel [{service client} {process client-1243}]
		21:10:46.606086 [I] Channel.Close called [{service client} {process client-1243}]
		21:10:46.606204 [D] Connection Close [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572}]
		21:10:46.606782 [D] checkExchanges updated connection state to connectionClosed [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572}]
		21:10:46.607228 [D] ConnectionCloseStateChange channel state = ChannelClosed connection minState = connectionClosed [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572}]
		21:10:46.607619 [D] Closing underlying network connection [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572}]
		21:10:46.607814 [D] Ignoring error after connection was closed: read tcp 127.0.0.1:51205->127.0.0.1:43572: use of closed network connection [{service client} {process client-1243} {connID 473} {localAddr 127.0.0.1:51205} {remoteAddr 127.0.0.1:43572}]
```

**Comment by prashantv** [comment]
Fixed by #458
