### ISSUE TITLE
Flaky tests (back again)

### ISSUE THREAD

**Issue by akshayjshah** [uber/tchannel-go#531]
Starting another issue to track flaky tests.

/cc @prashantv 

```
--- FAIL: TestPeerGetConnectionWithNoActiveConnections (0.03s)
	<autogenerated>:10: Unexpected log: [Warn]: Failed to add connection to peer. [{service testService} {process testService-45888} {hostPort 127.0.0.1:45888} {connID 468} {localAddr 127.0.0.1:45888} {remoteAddr 127.0.0.1:45122} {remoteHostPort 127.0.0.1:45122} {remoteIsEphemeral true} {remoteProcess testService-client-237} {remoteHostPort 127.0.0.1:45122} {direction inbound} {error tchannel error ErrCodeNetwork: connection is in an invalid state}]
	<autogenerated>:8: Debug logs:
		16:02:23.600023 [D] NewChannel created at goroutine 2812 [running]:
		github.com/uber/tchannel-go.getStacks(0xc422894100, 0xa51d7f, 0xb, 0xc421611f80)
			github.com/uber/tchannel-go/_test/_obj_test/introspection.go:468 +0xe5
		github.com/uber/tchannel-go.registerNewChannel(0xc422894140)
			github.com/uber/tchannel-go/_test/_obj_test/all_channels.go:39 +0x86
		github.com/uber/tchannel-go.NewChannel(0xa51d7f, 0xb, 0xc421e574c0, 0xa4eb3b, 0x1, 0xc4223068ea)
			github.com/uber/tchannel-go/_test/_obj_test/channel.go:211 +0xb57
		github.com/uber/tchannel-go/testutils.NewServerChannel(0xc421137e60, 0xc421611e30, 0xc421137e60, 0x0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/channel.go:51 +0x5d2
		github.com/uber/tchannel-go/testutils.newServer(0xcce5c0, 0xc421611e30, 0xc421137e60, 0x110)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/channel_t.go:71 +0x7c
		github.com/uber/tchannel-go/testutils.(*TestServer).addChannel(0xc421611e30, 0xaaf688, 0xc421137e60, 0x4)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:239 +0x72
		github.com/uber/tchannel-go/testutils.(*TestServer).NewServer(0xc421611e30, 0xc421e57a20, 0xc422351b00)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:204 +0xf4
		github.com/uber/tchannel-go/testutils.NewTestServer(0xcce700, 0xc420350180, 0xc421e57a20, 0x49197f)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:85 +0x2ca
		github.com/uber/tchannel-go/testutils.withServer(0xcce700, 0xc420350180, 0xc421e57a20, 0xc421e57ed0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:424 +0x51
		github.com/uber/tchannel-go/testutils.WithTestServer(0xcce700, 0xc420350180, 0x0, 0xc421e57ed0)
			/home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:111 +0x282
		github.com/uber/tchannel-go_test.WithVerifiedServer(0xc420350180, 0x0, 0xc421e57f20)
			/home/travis/gopath/src/github.com/uber/tchannel-go/verify_utils_test.go:63 +0x8f
		github.com/uber/tchannel-go_test.TestPeerGetConnectionWithNoActiveConnections(0xc420350180)
			/home/travis/gopath/src/github.com/uber/tchannel-go/peer_test.go:242 +0xe3
		testing.tRunner(0xc420350180, 0xaaf9f8)
			/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0xca
		created by testing.(*T).Run
			/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:646 +0x530
```

**Comment by prashantv** [comment]
Closing task since we don't have the full debug logs and it hasn't happened in the last ~5 PRs.
